"""
One-shot fixture generator for the Phase 1 Mock-backbone smoke loop.

Generates `data/renders/<sample_id>/` for every sample_id named in
`mapclass/configs/splits.json`. Each fixture matches `assert_sample_valid`:
  - flat.png (synthetic) or image.png (rumsey) — 64x64 random RGB
  - land_cover.png      — uint8 64x64, values in [0, 9)
  - topography.png      — uint8 64x64, values in [0, 3) plus 255 sentinel
                          where land_cover == water
  - manifest.json       — {source, source_subtype, ...}
  - sample_weights.json — {land_cover_weights, topography_weight}

Not part of the v1 ship pipeline. Lives under scripts/_ prefix so it stays
out of the public CLI surface.
"""
import json
from pathlib import Path

import numpy as np
from PIL import Image


REPO = Path(__file__).resolve().parent.parent
RENDERS = REPO / "data" / "renders"
SPLITS = REPO / "mapclass" / "configs" / "splits.json"

H = W = 64
NUM_LC = 9
NUM_TOPO = 3
WATER_IDX = 0  # LANDCOVER_CLASSES[0] == "water"
WATER_TOPO_SENTINEL = 255

SOURCE_META = {
    "synthetic_azgaar": {
        "source": "synthetic",
        "image_filename": "flat.png",
        "lc_weights": {"water": 1.0, "trees": 1.0, "shrubland": 1.0, "grassland": 1.0,
                       "cropland": 0.0, "built_up": 0.0, "bare_sparse": 1.0,
                       "flooded_wetland": 0.0, "snow_ice": 1.0},
        "topo_weight": 1.0,
    },
    "rumsey_registered": {
        "source": "historical",
        "image_filename": "image.png",
        "lc_weights": {"water": 1.0, "trees": 0.3, "shrubland": 0.7, "grassland": 0.7,
                       "cropland": 0.15, "built_up": 0.1, "bare_sparse": 1.0,
                       "flooded_wetland": 0.5, "snow_ice": 1.0},
        "topo_weight": 1.0,
    },
}


def make_fixture(sample_dir: Path, source_subtype: str, seed: int) -> None:
    """Image RGB encodes the labels so the Mock backbone has a learnable signal.

    Without structure (uniform-random labels) the 5-iter smoke loop fails the
    D-01 0.5% loss-decrease threshold because there's nothing to fit.
    """
    rng = np.random.default_rng(seed)
    meta = SOURCE_META[source_subtype]
    sample_dir.mkdir(parents=True, exist_ok=True)

    # Land cover label drives the red channel: each lc class maps to a distinct
    # red intensity band. Conv1 (3→32) can pick this up in 1-2 iters.
    lc = rng.integers(0, NUM_LC, size=(H, W), dtype=np.uint8)
    r = (lc.astype(np.uint16) * 28 + 8).clip(0, 255).astype(np.uint8)  # 8, 36, ..., 232
    g = rng.integers(0, 256, size=(H, W), dtype=np.uint8)
    b = rng.integers(0, 256, size=(H, W), dtype=np.uint8)
    img = np.stack([r, g, b], axis=-1)
    Image.fromarray(img, mode="RGB").save(sample_dir / meta["image_filename"])
    Image.fromarray(lc, mode="L").save(sample_dir / "land_cover.png")

    # Topography label drives the green channel similarly.
    topo = rng.integers(0, NUM_TOPO, size=(H, W), dtype=np.uint8)
    g_topo = (topo.astype(np.uint16) * 80 + 20).clip(0, 255).astype(np.uint8)
    img[:, :, 1] = g_topo
    Image.fromarray(img, mode="RGB").save(sample_dir / meta["image_filename"])
    topo[lc == WATER_IDX] = WATER_TOPO_SENTINEL  # mirror dem.py:_classify
    Image.fromarray(topo, mode="L").save(sample_dir / "topography.png")

    with open(sample_dir / "manifest.json", "w") as f:
        json.dump({
            "source": meta["source"],
            "source_subtype": source_subtype,
            "fixture": True,
            "fixture_note": "Generated by scripts/_make_smoke_fixtures.py — random data, Mock backbone only.",
        }, f, indent=2)

    with open(sample_dir / "sample_weights.json", "w") as f:
        json.dump({
            "land_cover_weights": meta["lc_weights"],
            "topography_weight": meta["topo_weight"],
        }, f, indent=2)


def main() -> None:
    splits = json.load(open(SPLITS))["by_split"]
    all_ids = sorted({sid for split in splits.values() for sid in split})
    print(f"=== Fixturing {len(all_ids)} samples under {RENDERS} ===")
    RENDERS.mkdir(parents=True, exist_ok=True)
    for i, sid in enumerate(all_ids):
        # Sample ID format: sample_NNNN_<source_subtype>
        source_subtype = sid.split("_", 2)[2]
        make_fixture(RENDERS / sid, source_subtype, seed=i)
    print(f"  done — {len(all_ids)} sample dirs at {RENDERS}")


if __name__ == "__main__":
    main()
